name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dependencies
        uses: ./.github/actions/dependencies

      - name: Build Playroom
        run: yarn build-playroom
        working-directory: ./packages/recipe

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
          workingDir: packages/recipe
          exitOnceUploaded: true
          onlyChanged: true # turbosnap (see https://www.chromatic.com/docs/turbosnap)
        env:
          STORYBOOK_INCLUDE_REGRESSION_STORIES: 1
