name: Code Quality
on: pull_request
jobs:
  validate:
    name: Code quality validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install
      
      - name: Typecheck
        run: yarn type-check

      - name: Run linters
        run: yarn lint
